# tmux show-options -g
# :source-file /etc/tmux.conf

set -g base-index 1
set -g history-limit 16400  # 48 MiB (applies after wordwrap)
set -g repeat-time 400
set -g clock-mode-colour colour11
set -g clock-mode-style 24
set -g pane-active-border-style fg=terminal,bg=colour4
set -g pane-border-style fg=colour5,bg=terminal
set -g pane-border-status off  # bottom
set -g status-style fg=colour3,bg=colour0
set -g status-interval 5
set -g status-justify left
set -g status-left "#(cat /proc/loadavg)"
set -g status-left-style fg=colour2
set -g status-left-length 15
set -g status-position top
set -g status-right "#(battery) %Y-%m-%d, %H:%M:%S"
set -g status-right-length 40

bind-key H pipe-pane -o "exec cat >>$HOME/log.tmux-$(date +%s)" \; display-message 'Toggled logging'
bind-key P command-prompt -p "save scrollback to: " -I '~/log.tmux-' 'capture-pane -e -S 2147483640; save-buffer %1; delete-buffer'
bind-key j command-prompt -p "join pane from:"  "join-pane -s :'%%'"

bind V \
	set -g mode-mouse on \;\
	set -g mouse-resize-pane on \;\
	set -g mouse-select-pane on \;\
	set -g mouse-select-window on \;\
	set -g pane-active-border-bg colour1 \;\
	display 'Mouse: ON'

bind v \
	set -g mode-mouse off \;\
	set -g mouse-resize-pane off \;\
	set -g mouse-select-pane off \;\
	set -g mouse-select-window off \;\
	set -g pane-active-border-bg colour0 \;\
	display 'Mouse: OFF'

unbind q
bind q \
	set -g -q status-position bottom \;\
	display-panes \;\
	run-shell 'sleep 0.98' \;\
	set -g -q status-position top

bind-key -r C-h resize-pane -L
bind-key -r C-j resize-pane -D
bind-key -r C-k resize-pane -U
bind-key -r C-l resize-pane -R
bind-key C-n next-window
bind-key C-p previous-window

