# not actually YAML but lets pretend:
# -*- mode: yaml -*-
# vim: ft=yaml:

# NOTE: when adding a comment at the end of a line,
#   there must be at least two spaces before the '#'

# NOTE: since the blockdevice of the bootdisk may get a different
#   name depending on the hardware it's booted on, "{hub}" can be
#   used instead of "sda" anywhere in the config file, so instead
#   of saying "/media/sda1/" it's better to say "/media/{hub}1/"

[global]
  z  # use mDNS + SSDP (noisy on the network); remove for stealth-mode
  name: hub  # the servername that's used for mDNS etc.
  p: 80,443  # serve http/https/webdav on these ports
  ftp: 21    # enable ftp-server on port 21 (spec-default)
  tftp: 69   # enable tftp-server on port 69 (spec-default)
  ftp4       # ftp: only listen on IPv4 (for buggy clients)
  tftp4      # tftp: only listen on IPv4 (for buggy clients)
  shr: /shr  # enable sharing (only works if password is enabled)
  df: 64M    # don't accept uploads if less than 64 MiB free
  wram       # allow upload into ramdisks (incl. removable storage)
  ed         # allow seeing dotfiles in folder listings
  dotsrch    # show dotfiles in search results
  ups-when   # everyone can see recent-upload times
  tail-who: 3  # everyone can use ?tail to stream growing files
  stats      # enable prometheus endpoint at /.cpr/metrics
  rss        # enable RSS output with `?rss` url suffix
  ver        # show version on controlpanel
  no-crt     # do not try to generate TLS cert on startup
  log-utc    # don't try to use local timezone (slightly faster)
  qrz: 1     # qr-code: small font
  qrp: 1     # qr-code: small border
  qri: .     # qr-code: use ip (disable mDNS-hostname)
  favico: 💾
  #lang: nor

  # enable the usb-eject feature
  xm: c1,/media/{hub}1/kit/res/usb-eject.py
  js-browser: /usb/{hub}1/kit/res/usb-eject.js

  # prevent accidental uploads into a ramdisk
  xbu: I,/media/{hub}1/kit/res/reject-ramdisk.py

  # these can make sense in some scenarios:
  #dedup      # enable symlink-based file deduplication; can be dangerous (if a regular filemanager or a unixshell is used to move a file, then deduplicated copies will bite the dust)
  #daw        # improve webdav support; can be dangerous (PUT-based uploads will be able to overwrite existing files)
  #log-conn   # verbose logging of tcp, in case of weird network issues
  #bak-flips  # log bitflips during uploads to the following folder:
  #bf-dir: /media/sdc/bitflips/

  # if running without persistent storage (without a 2nd partition on the flashdrive),
  # disable some security features which would be inconvenient during server restarts:
  #no-ses           # use plainext passwords in cookies (disable sessions)
  #fk-salt: fgsfds  # use a static well-known salt for filekeys
  #dk-salt: fgsfds  # ditto for dirkeys


# uncomment the two lines below to enable password-protection:

#[accounts]
#  u: hunter2   # leave "u" as it is, but replace "hunter2"

